[bar.default]
capsule = true
end = [ "media", "tray", "notifications", "brightness", "battery", "volume", "network", "control-center" ]
margin_ends = 0
radius = 0
shadow = false
start = [ "launcher", "workspaces", "active_window" ]
thickness = 32
widget_spacing = 8

[calendar]
enabled = true

    [calendar.account.radicale]
    provider = "custom"
    server_url = "http://srvr:5232/"
    type = "caldav"
    username = "paulm"

[dock]
auto_hide = true
enabled = true
reserve_space = false
show_instance_count = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1720.0
    cy = 1321.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 854.0
    cy = 841.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 630.0
    cy = 1240.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[shell]
avatar_path = "/home/paulm/dev/nixconf/pics/face.jpg"

    [shell.launcher]
    categories = false
    compact = true

    [shell.panel]
    open_near_click_control_center = true

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/paulm/dev/nixconf/pics"
enabled = true
fill_mode = "center"

    [wallpaper.default]
    path = "/home/paulm/dev/nixconf/pics/waves-light.jpg"

    [wallpaper.last]
    path = "/home/paulm/dev/nixconf/pics/waves-light.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/paulm/dev/nixconf/pics/waves-light.jpg"

[widget.workspaces]
empty_color = "on_primary"
focused_color = "tertiary"
occupied_color = "primary"
